from setuptools import setup


setup(
    name="oaemapi",
    version=open("app/version", "r").read(),
    description="Obstruction Adaptive Elevation Mask API (OAEM-API)",
    author="Gereon Tombrink",
    author_email="tombrink@igg.uni-bonn.de",
    url="https://github.com/gereon-t",
    license="MIT",
    long_description=open("README.md", "r").read(),
    long_description_content_type="text/markdown",
    keywords=[
        "sky obstruction",
        "elevation mask",
        "obstruction adaptive",
        "OAEM",
        "OAEM-API",
        "OAEM API",
        "GNSS",
    ],
    packages={"": "oaemapi"},
    package_data={"oaemapi": ["version", "LICENSE"]},
    zip_safe=False,
    python_requires=">=3.8",
    install_requires=[
        "anyio>=3.7.0",
        "attrs>=23.1.0",
        "certifi>=2023.5.7",
        "charset-normalizer>=3.1.0",
        "click>=8.1.3",
        "click-plugins>=1.1.1",
        "cligj>=0.7.2",
        "fastapi>=0.96.1",
        "Fiona>=1.9.4.post1",
        "geopandas>=0.13.2",
        "h11>=0.14.0",
        "idna>=3.4",
        "intervaltree>=3.1.0",
        "Jinja2>=3.1.2",
        "MarkupSafe>=2.1.3",
        "numpy>=1.24.3",
        "packaging>=23.1",
        "pandas>=2.0.2",
        "plotly>=5.15.0",
        "pointset>=0.1.5",
        "pvlib>=0.10.0",
        "pydantic>=1.10.9",
        "pyproj>=3.5.0",
        "python-dateutil>=2.8.2",
        "pytz>=2023.3",
        "requests>=2.31.0",
        "scipy>=1.10.1",
        "shapely>=2.0.1",
        "six>=1.16.0",
        "sniffio>=1.3.0",
        "sortedcontainers>=2.4.0",
        "starlette>=0.27.0",
        "tenacity>=8.2.2",
        "typing_extensions>=4.6.3",
        "tzdata>=2023.3",
        "urllib3>=2.0.3",
        "uvicorn>=0.22.0",
        "xmltodict>=0.13.0",
    ],
)
